spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: projectinformatic6666@gmail.com
    password: wqjhpbrjotkrjetd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
